"""Add issue tracker tables

Revision ID: 8619a22eed23
Revises:
Create Date: 2025-11-11 18:24:14.100288

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8619a22eed23"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "issues",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("project_id", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("assignee", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column("epic_id", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("closed_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_issues_assignee"), "issues", ["assignee"], unique=False)
    op.create_index(op.f("ix_issues_closed_at"), "issues", ["closed_at"], unique=False)
    op.create_index(op.f("ix_issues_created_at"), "issues", ["created_at"], unique=False)
    op.create_index(op.f("ix_issues_epic_id"), "issues", ["epic_id"], unique=False)
    op.create_index(op.f("ix_issues_priority"), "issues", ["priority"], unique=False)
    op.create_index(op.f("ix_issues_project_id"), "issues", ["project_id"], unique=False)
    op.create_index(op.f("ix_issues_status"), "issues", ["status"], unique=False)
    op.create_index(op.f("ix_issues_type"), "issues", ["type"], unique=False)
    op.create_index(op.f("ix_issues_updated_at"), "issues", ["updated_at"], unique=False)
    op.create_table(
        "labels",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("project_id", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("color", sqlmodel.sql.sqltypes.AutoString(length=7), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_labels_name"), "labels", ["name"], unique=False)
    op.create_index(op.f("ix_labels_project_id"), "labels", ["project_id"], unique=False)
    op.create_table(
        "comments",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("issue_id", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("author", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("content", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["issue_id"],
            ["issues.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_comments_author"), "comments", ["author"], unique=False)
    op.create_index(op.f("ix_comments_created_at"), "comments", ["created_at"], unique=False)
    op.create_index(op.f("ix_comments_issue_id"), "comments", ["issue_id"], unique=False)
    op.create_table(
        "dependencies",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("from_issue_id", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("to_issue_id", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["from_issue_id"],
            ["issues.id"],
        ),
        sa.ForeignKeyConstraint(
            ["to_issue_id"],
            ["issues.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_dependencies_from_issue_id"), "dependencies", ["from_issue_id"], unique=False)
    op.create_index(op.f("ix_dependencies_to_issue_id"), "dependencies", ["to_issue_id"], unique=False)
    op.create_index(op.f("ix_dependencies_type"), "dependencies", ["type"], unique=False)
    op.create_table(
        "epics",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("project_id", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("start_date", sa.DateTime(), nullable=True),
        sa.Column("target_date", sa.DateTime(), nullable=True),
        sa.Column("completed_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"],
            ["issues.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_epics_project_id"), "epics", ["project_id"], unique=False)
    op.create_index(op.f("ix_epics_status"), "epics", ["status"], unique=False)
    op.create_table(
        "issue_labels",
        sa.Column("issue_id", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("label_name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["issue_id"],
            ["issues.id"],
        ),
        sa.PrimaryKeyConstraint("issue_id", "label_name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("issue_labels")
    op.drop_index(op.f("ix_epics_status"), table_name="epics")
    op.drop_index(op.f("ix_epics_project_id"), table_name="epics")
    op.drop_table("epics")
    op.drop_index(op.f("ix_dependencies_type"), table_name="dependencies")
    op.drop_index(op.f("ix_dependencies_to_issue_id"), table_name="dependencies")
    op.drop_index(op.f("ix_dependencies_from_issue_id"), table_name="dependencies")
    op.drop_table("dependencies")
    op.drop_index(op.f("ix_comments_issue_id"), table_name="comments")
    op.drop_index(op.f("ix_comments_created_at"), table_name="comments")
    op.drop_index(op.f("ix_comments_author"), table_name="comments")
    op.drop_table("comments")
    op.drop_index(op.f("ix_labels_project_id"), table_name="labels")
    op.drop_index(op.f("ix_labels_name"), table_name="labels")
    op.drop_table("labels")
    op.drop_index(op.f("ix_issues_updated_at"), table_name="issues")
    op.drop_index(op.f("ix_issues_type"), table_name="issues")
    op.drop_index(op.f("ix_issues_status"), table_name="issues")
    op.drop_index(op.f("ix_issues_project_id"), table_name="issues")
    op.drop_index(op.f("ix_issues_priority"), table_name="issues")
    op.drop_index(op.f("ix_issues_epic_id"), table_name="issues")
    op.drop_index(op.f("ix_issues_created_at"), table_name="issues")
    op.drop_index(op.f("ix_issues_closed_at"), table_name="issues")
    op.drop_index(op.f("ix_issues_assignee"), table_name="issues")
    op.drop_table("issues")
    # ### end Alembic commands ###
