language: en-US

reviews:
  profile: assertive
  request_changes_workflow: true
  high_level_summary: true
  high_level_summary_instructions: "Generate a bullet-list summary of key changes and items requiring design discussion."
  high_level_summary_placeholder: "@coderabbitai summary"
  high_level_summary_in_walkthrough: false
  auto_title_placeholder: "@coderabbitai"
  auto_title_instructions: "Create a concise descriptive title under 50 characters following ‘<area>: <action>’ format."
  review_status: true
  commit_status: true
  fail_commit_status: true
  collapse_walkthrough: false
  changed_files_summary: true
  sequence_diagrams: true
  estimate_code_review_effort: true
  assess_linked_issues: true
  related_issues: true
  related_prs: true
  suggested_labels: true
  auto_apply_labels: false
  suggested_reviewers: true
  auto_assign_reviewers: false
  in_progress_fortune: false
  poem: false
  path_filters: []
  path_instructions:
    - path: "**/*.py"
      instructions: |
        Apply Python-specific guidelines: typing, dataclasses, EAFP, context managers, pathlib, etc.
    - path: "infra/**"
      instructions: |
        Ensure infra layer uses abstractions and doesn’t mix domain logic.
  abort_on_close: true
  disable_cache: false
  auto_review:
    enabled: true
    auto_incremental_review: true
    ignore_title_keywords: []
    labels: []
    drafts: false
    base_branches: []
    ignore_usernames: []

finishing_touches:
  docstrings:
    enabled: true
  unit_tests:
    enabled: true

pre_merge_checks:
  docstrings:
    mode: warning
    threshold: 80
  title:
    mode: warning
    requirements: "Title should be under 50 chars in format '<area>: <action>'."
  description:
    mode: warning
  issue_assessment:
    mode: warning
  custom_checks:
    - name: "SRP‐enforcement"
      mode: error
      instructions: "All modules, classes, and functions must follow the Single Responsibility Principle: one reason to change. Flag if more than one area of concern is addressed."
    - name: "Layer‐boundary‐violation"
      mode: error
      instructions: "Domain layer must not import from infra/api/cli; infra/adapters must not import domain internals. Flag any import crossing these boundaries."
    - name: "Magic‐values"
      mode: warning
      instructions: "Check for magic numbers or strings in code; constants or config references should be used instead."

tools:
  ast-grep:
    rule_dirs: []
    util_dirs: []
    essential_rules: true
    packages: []
  shellcheck:
    enabled: true
  ruff:
    enabled: true
  markdownlint:
    enabled: true
  github-checks:
    enabled: true
    timeout_ms: 90000

knowledge_base:
  web_search:
    enabled: true
  code_guidelines:
    enabled: true
    filePatterns:
      - "best-practices-check.prompt.md"
      - "code-analysis.prompt.md"
      - "pythonic-code.prompt.md"

code_generation:
  docstrings:
    language: en-US
    path_instructions:
      - path: "**/*.py"
        instructions: "Generate full docstrings for modules, classes and functions following Google style."
  unit_tests:
    path_instructions:
      - path: "src/**/*.py"
        instructions: "Generate pytest tests covering edge cases, business logic, and error handling."

