"""Main CLI entry point for glorious-agents."""

import logging
from pathlib import Path

import typer
from rich.console import Console

from glorious_agents.config import config
from glorious_agents.core.loader import load_all_skills
from glorious_agents.core.registry import get_registry

logger = logging.getLogger(__name__)

app = typer.Typer(
    name="agent",
    help="Glorious Agents - Modular skill-based agent framework",
    no_args_is_help=True,
)
console = Console()


def init_app() -> None:
    """Initialize the application by loading all skills.

    Discovers and loads all available skills from the configured skills directory
    and from installed Python packages via entry points. Each loaded skill is
    mounted as a subcommand in the main CLI application.

    Raises:
        Exception: If any error occurs during skill loading or mounting. The error
            is logged and re-raised after displaying a user-friendly message.

    Example:
        >>> init_app()
        # Skills loaded and mounted as subcommands
    """
    try:
        load_all_skills()

        # Mount loaded skills as subcommands
        registry = get_registry()
        for manifest in registry.list_all():
            skill_app = registry.get_app(manifest.name)
            if skill_app:
                app.add_typer(skill_app, name=manifest.name)
    except Exception as e:
        logger.error(f"Error initializing skills: {e}", exc_info=True)
        console.print(f"[red]Error initializing skills:[/red] {e}")
        raise


@app.command()
def version() -> None:
    """Show version information for Glorious Agents.

    Displays the current version number of the Glorious Agents framework.
    The version is imported dynamically from the package metadata.

    Example:
        $ agent version
        Glorious Agents v0.1.0
    """
    from glorious_agents import __version__

    console.print(f"Glorious Agents v{__version__}")


@app.command()
def init() -> None:
    """Initialize agent workspace by generating AGENT-TOOLS.md and updating AGENTS.md.

    Creates or updates AGENT-TOOLS.md with descriptions of all available skills,
    and ensures AGENTS.md references this file. This helps AI agents understand
    what tools are available in the current workspace.

    Example:
        $ agent init
        Generated AGENT-TOOLS.md with 5 skills
        Updated AGENTS.md with reference
    """
    from glorious_agents.core.db import get_connection

    # Ensure skills are loaded
    registry = get_registry()
    skills = registry.list_all()

    if not skills:
        console.print("[yellow]No skills loaded. Loading skills...[/yellow]")
        load_all_skills()
        skills = registry.list_all()

    # Generate AGENT-TOOLS.md
    agent_tools_path = Path.cwd() / "AGENT-TOOLS.md"
    console.print(f"[blue]Generating {agent_tools_path}...[/blue]")

    content = ["# Agent Tools", ""]
    content.append(
        "> **Note**: This file is automatically generated by `agent init`. Do not edit manually."
    )
    content.append("")
    content.append(
        "This document describes all available skills/tools in this agent workspace."
    )
    content.append("")

    for skill in skills:
        manifest = registry.get_manifest(skill.name)
        if not manifest:
            continue

        # Skill header
        content.append(f"## {manifest.name}")
        content.append("")
        content.append(f"**Version**: {manifest.version}")
        content.append("")
        content.append(f"**Description**: {manifest.description}")
        content.append("")

        # Dependencies
        if manifest.requires:
            content.append(f"**Requires**: {', '.join(manifest.requires)}")
            content.append("")

        # Commands
        app_obj = registry.get_app(skill.name)
        if app_obj and hasattr(app_obj, "registered_commands"):
            content.append("**Commands**:")
            content.append("")
            for cmd in app_obj.registered_commands:
                cmd_name = cmd.name or cmd.callback.__name__
                cmd_help = cmd.help or cmd.callback.__doc__ or "No description"
                cmd_help_line = cmd_help.split("\n")[0].strip()
                content.append(f"- `{cmd_name}`: {cmd_help_line}")
            content.append("")

        # Database info
        if manifest.requires_db:
            try:
                conn = get_connection()
                skill_table_prefix = skill.name.replace("-", "_")
                cur = conn.execute(
                    "SELECT name FROM sqlite_master WHERE type='table' AND name LIKE ?",
                    (f"{skill_table_prefix}%",),
                )
                tables = [row[0] for row in cur.fetchall()]
                if tables:
                    content.append(f"**Database Tables**: {', '.join(tables)}")
                    content.append("")
            except Exception:
                pass

        # Documentation
        if manifest.external_doc and manifest.path:
            usage_path = Path(manifest.path) / manifest.external_doc
            if usage_path.exists():
                content.append("**Usage Documentation**:")
                content.append("")
                content.append("```")
                content.append(usage_path.read_text().strip())
                content.append("```")
                content.append("")

        content.append("---")
        content.append("")

    agent_tools_path.write_text("\n".join(content))
    console.print(f"[green]✓ Generated {agent_tools_path} with {len(skills)} skills[/green]")

    # Update AGENTS.md
    agents_md_path = Path.cwd() / "AGENTS.md"
    reference_text = "See [AGENT-TOOLS.md](./AGENT-TOOLS.md) for available tools and skills."

    if agents_md_path.exists():
        content_str = agents_md_path.read_text()
        if reference_text not in content_str:
            # Add reference at the end
            updated_content = content_str.rstrip() + "\n\n" + reference_text + "\n"
            agents_md_path.write_text(updated_content)
            console.print(f"[green]✓ Updated {agents_md_path} with reference[/green]")
        else:
            console.print(f"[dim]✓ {agents_md_path} already contains reference[/dim]")
    else:
        # Create new AGENTS.md
        agents_md_path.write_text(f"# Agent Instructions\n\n{reference_text}\n")
        console.print(f"[green]✓ Created {agents_md_path}[/green]")


@app.command()
def daemon(
    host: str = typer.Option(config.DAEMON_HOST, help="Host to bind to"),
    port: int = typer.Option(config.DAEMON_PORT, help="Port to bind to"),
) -> None:
    """Start the FastAPI daemon for RPC access.

    Launches a background FastAPI server that provides HTTP access to skills
    and allows remote procedure calls to skill methods. The daemon enables
    efficient long-running operations and allows external systems to interact
    with the agent framework.

    Available Endpoints:
        GET  /skills - List all loaded skills
        POST /rpc/{skill}/{method} - Call a skill method with JSON params
        POST /events/{topic} - Publish an event to the event bus
        GET  /events/topics - List all active event topics
        GET  /cache/{key} - Retrieve a cached value
        PUT  /cache/{key} - Store a value in the cache
        DELETE /cache/{key} - Delete a cache entry
        GET  /cache - Get cache statistics

    Args:
        host: The hostname or IP address to bind the server to. Defaults to
            the value from GLORIOUS_DAEMON_HOST config (typically '127.0.0.1').
        port: The port number to bind the server to. Defaults to the value
            from GLORIOUS_DAEMON_PORT config (typically 8765).

    Example:
        $ agent daemon --host 0.0.0.0 --port 8080
        # Starts daemon accessible on all interfaces at port 8080

        # Access the API:
        $ curl http://localhost:8765/skills
        $ curl -X POST http://localhost:8765/rpc/notes/list_notes -H "Content-Type: application/json" -d '{}'
    """
    from glorious_agents.core.daemon import run_daemon

    run_daemon(host, port)


def main() -> None:
    """Main entry point for the Glorious Agents CLI.

    This function is the primary entry point invoked when running the 'agent'
    command. It performs the following initialization steps:

    1. Imports and registers management CLI modules (skills, identity)
    2. Loads and mounts all discovered skills as subcommands
    3. Starts the Typer CLI application to process user commands

    The function is typically called automatically when the package is installed
    and invoked via the 'agent' console script entry point.

    Example:
        $ agent --help
        $ agent skills list
        $ agent identity whoami
    """
    # Import management CLIs
    from glorious_agents import identity_cli, skills_cli

    # Add management commands
    app.add_typer(skills_cli.app, name="skills")
    app.add_typer(identity_cli.app, name="identity")

    # Initialize and load skills
    init_app()

    # Run CLI
    app()


if __name__ == "__main__":
    main()
